name: b2b-license-platform
services:
- name: web
  environment_slug: node-js
  github:
    repo: your-repo
    branch: main
  build_command: node digitalocean-server-final.cjs --build-only
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /health
    initial_delay_seconds: 30
    period_seconds: 15
    timeout_seconds: 10
    success_threshold: 1
    failure_threshold: 5
  domains:
  - domain: clownfish-app-iarak.ondigitalocean.app
    type: PRIMARY
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"