name: b2b-license-platform
services:
- name: web
  environment_slug: node-js
  github:
    repo: your-repo
    branch: main
  run_command: npm start
  build_command: mkdir -p dist && cp index.js dist/index.js && npm install
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  health_check:
    http_path: /health
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
  routes:
  - path: /
  - path: /health
  - path: /eur
  - path: /km
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"