name: b2b-license-platform
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
  run_command: npm start
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  dockerfile_path: Dockerfile.digitalocean
  
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: SESSION_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: SENTRY_DSN
    scope: RUN_TIME
    type: SECRET
    
  health_check:
    http_path: /api/health
    
databases:
- name: db
  engine: PG
  version: "14"
  size: basic-xs
  num_nodes: 1