version: '3.8'

services:
  # Core API Service
  core-api:
    build: ./core-api-service
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CORE_API_PORT=5003
      - INTERNAL_SERVICE_KEY=${INTERNAL_SERVICE_KEY}
      - NODE_ENV=${NODE_ENV}
    networks:
      - microservices

  # Admin Service
  admin-service:
    build: ./admin-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_PORT=5001
      - CORE_API_URL=http://core-api:5003
      - ADMIN_SESSION_SECRET=${ADMIN_SESSION_SECRET}
      - INTERNAL_SERVICE_KEY=${INTERNAL_SERVICE_KEY}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - core-api
    networks:
      - microservices

  # B2B Service
  b2b-service:
    build: ./b2b-service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - B2B_PORT=5002
      - CORE_API_URL=http://core-api:5003
      - B2B_SESSION_SECRET=${B2B_SESSION_SECRET}
      - INTERNAL_SERVICE_KEY=${INTERNAL_SERVICE_KEY}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - core-api
    networks:
      - microservices

networks:
  microservices:
    driver: bridge